abstract class ShopStates{}
class InitialState extends ShopStates{}
class NavBarState extends ShopStates{}
class HomeModelLoading extends ShopStates{}
class HomeModelSuccess extends ShopStates{}
class HomeModelError extends ShopStates{}
class GetCategoriesSuccess extends ShopStates{}
class GetCategoriesError extends ShopStates{}
class GetCategoriesLoading extends ShopStates{}
class SetFavSuccess extends ShopStates{}
class SetFavSError extends ShopStates{}
class GetProfileSuccess extends ShopStates{}
class GetProfileError extends ShopStates{}
class GetProfileLoading extends ShopStates{}
class UpdateProfileSuccess extends ShopStates{}
class UpdateProfileError extends ShopStates{}
class UpdateProfileLoading extends ShopStates{}
class SearchSuccess extends ShopStates{}
class SearchError extends ShopStates{}
class SearchLoading extends ShopStates{}